version: '3'
services:
  app:
    image: first-nuxt-yarn
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    environment:
      HOST: "0.0.0.0"
    env_file: .env
    ports:
      - 3000:3000
    command: ["run", "dev"]
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
  yarn:
    image: first-nuxt-yarn
    build:
      context: .
      dockerfile: docker/yarn/Dockerfile
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
  vue:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
volumes:
  node-modules-volume:
